version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - ./backend/.env
#    ports:
#      - "5251:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm run start"
      

  db:
    image: mongo
    env_file:
      - ./backend/.env
#    ports:
#      - "27019:27017"
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init:/docket-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure


  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/front
      - ./nginx.conf:/etc/nginx/conf.d/default.conf